import { L, type BilingualText } from "./labels.js";

/** Chrome strings for bilingual summary display (copy uses .zh only). */
export const SUMMARY_COPY = {
  informant: L("答題者", {
    en: "Who answered",
    vi: "Người trả lời",
    id: "Yang menjawab",
    ja: "回答者",
    ko: "답변자",
    fil: "Sumagot",
    th: "ผู้ตอบ",
    de: "Antwortende Person",
    fr: "Qui a répondu",
    es: "Quién respondió",
  }),
  chief: L("主訴", {
    en: "Chief complaint",
    vi: "Lý do chính",
    id: "Keluhan utama",
    ja: "主訴",
    ko: "주호소",
    fil: "Pangunahing reklamo",
    th: "อาการหลัก",
    de: "Hauptbeschwerde",
    fr: "Plainte principale",
    es: "Motivo principal",
  }),
  sense: L("還有其他感覺不舒服的地方", {
    en: "Anywhere else that feels uncomfortable",
    vi: "Chỗ nào khác còn khó chịu",
    id: "Tempat lain yang terasa tidak nyaman",
    ja: "他に具合の悪い所",
    ko: "다른 불편한 곳",
    fil: "Ibang parte na hindi komportable",
    th: "ที่อื่นที่ยังรู้สึกไม่สบาย",
    de: "Andere unangenehme Stellen",
    fr: "Autres endroits inconfortables",
    es: "Otros lugares incómodos",
  }),
  notObtained: L("未取得", {
    en: "Not obtained",
    vi: "Chưa có",
    id: "Belum didapat",
    ja: "未取得",
    ko: "미확보",
    fil: "Hindi nakuha",
    th: "ยังไม่ได้",
    de: "Nicht erhoben",
    fr: "Non obtenu",
    es: "No obtenido",
  }),
  notObtainedUnknown: L("未取得（不知道）", {
    en: "Not obtained (unknown)",
    vi: "Chưa có (không biết)",
    id: "Belum didapat (tidak tahu)",
    ja: "未取得（わからない）",
    ko: "미확보 (모름)",
    fil: "Hindi nakuha (hindi alam)",
    th: "ยังไม่ได้ (ไม่ทราบ)",
    de: "Nicht erhoben (unbekannt)",
    fr: "Non obtenu (ne sait pas)",
    es: "No obtenido (no sabe)",
  }),
  notObtainedSkipped: L("未取得（跳過）", {
    en: "Not obtained (skipped)",
    vi: "Chưa có (bỏ qua)",
    id: "Belum didapat (dilewati)",
    ja: "未取得（スキップ）",
    ko: "미확보 (건너뜀)",
    fil: "Hindi nakuha (nilaktawan)",
    th: "ยังไม่ได้ (ข้าม)",
    de: "Nicht erhoben (übersprungen)",
    fr: "Non obtenu (passé)",
    es: "No obtenido (omitido)",
  }),
  body: L("部位", {
    en: "Location",
    vi: "Vị trí",
    id: "Lokasi",
    ja: "部位",
    ko: "부위",
    fil: "Bahagi",
    th: "ตำแหน่ง",
    de: "Stelle",
    fr: "Zone",
    es: "Zona",
  }),
  quality: L("性質", {
    en: "Quality",
    vi: "Tính chất",
    id: "Sifat",
    ja: "性状",
    ko: "양상",
    fil: "Uri",
    th: "ลักษณะ",
    de: "Art",
    fr: "Nature",
    es: "Carácter",
  }),
  time: L("時間", {
    en: "Duration",
    vi: "Thời gian",
    id: "Durasi",
    ja: "時間",
    ko: "시간",
    fil: "Tagal",
    th: "เวลา",
    de: "Dauer",
    fr: "Durée",
    es: "Duración",
  }),
  refine: L("細調", {
    en: "EMT note",
    vi: "Ghi chú EMT",
    id: "Catatan EMT",
    ja: "詳細",
    ko: "세부",
    fil: "Tala ng EMT",
    th: "รายละเอียด",
    de: "EMT-Notiz",
    fr: "Note SMT",
    es: "Nota TEM",
  }),
  pain: L("痛尺", {
    en: "Pain score",
    vi: "Mức đau",
    id: "Skala nyeri",
    ja: "痛みの強さ",
    ko: "통증 점수",
    fil: "Antas ng sakit",
    th: "ระดับปวด",
    de: "Schmerzskala",
    fr: "Douleur",
    es: "Dolor",
  }),
  otherBody: L("其他部位", {
    en: "Other location",
    vi: "Vị trí khác",
    id: "Lokasi lain",
    ja: "その他の部位",
    ko: "다른 부위",
    fil: "Ibang bahagi",
    th: "ตำแหน่งอื่น",
    de: "Andere Stelle",
    fr: "Autre zone",
    es: "Otra zona",
  }),
  note: L("備註", {
    en: "Note",
    vi: "Ghi chú",
    id: "Catatan",
    ja: "備考",
    ko: "비고",
    fil: "Tala",
    th: "หมายเหตุ",
    de: "Notiz",
    fr: "Note",
    es: "Nota",
  }),
  midChange: L("中途變更", {
    en: "Changed mid-case",
    vi: "Đổi giữa chừng",
    id: "Berubah di tengah",
    ja: "途中で変更",
    ko: "중간에 변경",
    fil: "Pinalitan sa gitna",
    th: "เปลี่ยนระหว่างทาง",
    de: "Unterwegs geändert",
    fr: "Changé en cours",
    es: "Cambió durante el caso",
  }),
  title: L("現場資訊彙整", {
    en: "Field summary",
    vi: "Tóm tắt hiện trường",
    id: "Ringkasan lapangan",
    ja: "現場情報のまとめ",
    ko: "현장 정보 요약",
    fil: "Buod sa lugar",
    th: "สรุปข้อมูลหน้างาน",
    de: "Einsatzübersicht",
    fr: "Synthèse terrain",
    es: "Resumen de campo",
  }),
  eyebrow: L("本機摘要", {
    en: "On-device summary",
    vi: "Tóm tắt trên máy",
    id: "Ringkasan di perangkat",
    ja: "端末上の要約",
    ko: "기기 내 요약",
    fil: "Buod sa device",
    th: "สรุปในเครื่อง",
    de: "Geräteinterne Zusammenfassung",
    fr: "Résumé sur l'appareil",
    es: "Resumen en el dispositivo",
  }),
  lead: L("可複製後貼到紀錄；結束即清除。", {
    en: "Copy into your record; finishing clears this case.",
    vi: "Có thể sao chép vào hồ sơ; kết thúc sẽ xóa.",
    id: "Salin ke catatan; selesai akan menghapus.",
    ja: "記録に貼り付け可。終了で消去。",
    ko: "기록에 붙여넣기 가능. 종료 시 삭제.",
    fil: "Kopyahin sa record; matatapos ay mabubura.",
    th: "คัดลอกไปบันทึกได้; จบแล้วล้าง",
    de: "In die Dokumentation kopieren; Beenden löscht den Fall.",
    fr: "Copier dans le dossier ; terminer efface le cas.",
    es: "Copiar al registro; al terminar se borra.",
  }),
  edit: L("編輯", {
    en: "Edit",
    vi: "Sửa",
    id: "Ubah",
    ja: "編集",
    ko: "편집",
    fil: "I-edit",
    th: "แก้ไข",
    de: "Bearbeiten",
    fr: "Modifier",
    es: "Editar",
  }),
  copyHint: L("複製為中文", {
    en: "Copy in Chinese",
    vi: "Sao chép tiếng Trung",
    id: "Salin dalam bahasa Cina",
    ja: "中国語でコピー",
    ko: "중국어로 복사",
    fil: "Kopyahin sa Chinese",
    th: "คัดลอกเป็นภาษาจีน",
    de: "Auf Chinesisch kopieren",
    fr: "Copier en chinois",
    es: "Copiar en chino",
  }),
} as const satisfies Record<string, BilingualText>;
