import { L, type BilingualText } from "./labels.js";

export const UI_COPY = {
  cc1Title: L("哪裡／怎麼了？", {
    en: "Where / what is wrong?",
    vi: "Đau ở đâu / chuyện gì?",
    id: "Di mana / ada apa?",
    ja: "どこが／どうしましたか？",
    ko: "어디가 / 무슨 일인가요?",
    fil: "Saan / ano ang problema?",
    th: "ตรงไหน / เป็นอะไร?",
  }),
  cc1What: L("怎麼了", {
    en: "What is wrong?",
    vi: "Chuyện gì?",
    id: "Ada apa?",
    ja: "どうしましたか",
    ko: "무슨 일인가요",
    fil: "Ano ang problema",
    th: "เป็นอะไร",
  }),
  cc1Where: L("哪裡", {
    en: "Where?",
    vi: "Ở đâu?",
    id: "Di mana?",
    ja: "どこ",
    ko: "어디",
    fil: "Saan",
    th: "ตรงไหน",
  }),
  cc1WhereOptional: L("（此主訴類型可不選部位）", {
    en: "(Body map optional for this complaint)",
    vi: "(Loại này có thể bỏ qua vị trí)",
    id: "(Peta tubuh opsional untuk keluhan ini)",
    ja: "（この訴えでは部位は任意）",
    ko: "(이 증상은 부위 선택 선택 사항)",
    fil: "(Opsyonal ang bahagi ng katawan)",
    th: "(อาการนี้ไม่จำเป็นต้องชี้ตำแหน่ง)",
  }),
  cc2Title: L("怎麼不舒服／多久了？", {
    en: "How does it feel / how long?",
    vi: "Cảm giác thế nào / bao lâu?",
    id: "Rasanya bagaimana / sudah berapa lama?",
    ja: "どんな感じ／どのくらい？",
    ko: "어떤 느낌 / 얼마나 됐나요?",
    fil: "Ano ang pakiramdam / gaano katagal?",
    th: "รู้สึกอย่างไร / นานแค่ไหน?",
  }),
  cc2Quality: L("性質", {
    en: "Quality",
    vi: "Tính chất",
    id: "Sifat keluhan",
    ja: "性状",
    ko: "양상",
    fil: "Uri ng pakiramdam",
    th: "ลักษณะ",
  }),
  cc2Duration: L("多久了 · 時長", {
    en: "How long · Duration",
    vi: "Bao lâu",
    id: "Durasi",
    ja: "どのくらい・時間",
    ko: "얼마나 · 기간",
    fil: "Gaano katagal",
    th: "นานแค่ไหน",
  }),
  cc2Period: L("或時段", {
    en: "Or period",
    vi: "Hoặc khoảng thời gian",
    id: "Atau periode",
    ja: "または時間帯",
    ko: "또는 시간대",
    fil: "O oras/panahon",
    th: "หรือช่วงเวลา",
  }),
  cc2Pain: L("疼痛指數 · Pain 1–10", {
    en: "Pain score 1–10",
    vi: "Mức đau 1–10",
    id: "Skala nyeri 1–10",
    ja: "痛みの強さ 1–10",
    ko: "통증 점수 1–10",
    fil: "Antas ng sakit 1–10",
    th: "ระดับปวด 1–10",
  }),
  senseTitle: L("還有其他不舒服嗎？", {
    en: "Any other discomfort?",
    vi: "Còn khó chịu nào khác?",
    id: "Ada keluhan lain?",
    ja: "他に具合の悪い所は？",
    ko: "다른 불편한 곳이 있나요?",
    fil: "May iba pa bang hindi komportable?",
    th: "ยังมีอาการอื่นอีกไหม?",
  }),
  senseLead: L("一輪二次掃描", {
    en: "One extra pass",
    vi: "Chỉ hỏi thêm một lần",
    id: "Satu kali pemeriksaan tambahan",
    ja: "追加で一回だけ確認",
    ko: "한 번 더 확인",
    fil: "Isang karagdagang check",
    th: "ตรวจถามเพิ่มอีกครั้ง",
  }),
  senseSymptoms: L("伴隨症狀", {
    en: "Accompanying",
    vi: "Triệu chứng kèm theo",
    id: "Gejala penyerta",
    ja: "随伴症状",
    ko: "동반 증상",
    fil: "Kasamang sintomas",
    th: "อาการร่วม",
  }),
  senseBody: L("可再指部位", {
    en: "Optional body scan",
    vi: "Có thể chỉ thêm vị trí",
    id: "Boleh tunjuk bagian tubuh lagi",
    ja: "部位を追加で指せます",
    ko: "부위를 더 가리킬 수 있음",
    fil: "Puwedeng tumuro ulit ng bahagi",
    th: "ชี้ตำแหน่งเพิ่มได้",
  }),
} as const satisfies Record<string, BilingualText>;
