import { L, type BilingualText } from "./labels.js";

export const UI_COPY = {
  cc1Title: L("哪裡／怎麼了？", {
    en: "Where / what is wrong?",
    vi: "Đau ở đâu / chuyện gì?",
    id: "Di mana / ada apa?",
    ja: "どこが／どうしましたか？",
    ko: "어디가 / 무슨 일인가요?",
    fil: "Saan / ano ang problema?",
    th: "ตรงไหน / เป็นอะไร?",
      de: "Wo / was ist los?",
      fr: "Où / que se passe-t-il ?",
      es: "¿Dónde / qué ocurre?",
    }),
  cc1What: L("怎麼了", {
    en: "What is wrong?",
    vi: "Chuyện gì?",
    id: "Ada apa?",
    ja: "どうしましたか",
    ko: "무슨 일인가요",
    fil: "Ano ang problema",
    th: "เป็นอะไร",
      de: "Was ist los?",
      fr: "Que se passe-t-il ?",
      es: "¿Qué ocurre?",
    }),
  cc1Where: L("哪裡", {
    en: "Where?",
    vi: "Ở đâu?",
    id: "Di mana?",
    ja: "どこ",
    ko: "어디",
    fil: "Saan",
    th: "ตรงไหน",
      de: "Wo?",
      fr: "Où ?",
      es: "¿Dónde?",
    }),
  cc1WhereOptional: L("（此主訴類型可不選部位）", {
    en: "(Body map optional for this complaint)",
    vi: "(Loại này có thể bỏ qua vị trí)",
    id: "(Peta tubuh opsional untuk keluhan ini)",
    ja: "（この訴えでは部位は任意）",
    ko: "(이 증상은 부위 선택 선택 사항)",
    fil: "(Opsyonal ang bahagi ng katawan)",
    th: "(อาการนี้ไม่จำเป็นต้องชี้ตำแหน่ง)",
      de: "(Körperkarte bei dieser Beschwerde optional)",
      fr: "(Carte du corps facultative pour cette plainte)",
      es: "(Mapa corporal opcional para esta molestia)",
    }),
  ccQualityTitle: L("怎麼不舒服？", {
    en: "How does it feel?",
    vi: "Cảm giác thế nào?",
    id: "Rasanya bagaimana?",
    ja: "どんな感じですか？",
    ko: "어떤 느낌인가요?",
    fil: "Ano ang pakiramdam?",
    th: "รู้สึกอย่างไร?",
      de: "Wie fühlt es sich an?",
      fr: "Quelle sensation ?",
      es: "¿Cómo se siente?",
    }),
  ccQuality: L("性質", {
    en: "Quality",
    vi: "Tính chất",
    id: "Sifat keluhan",
    ja: "性状",
    ko: "양상",
    fil: "Uri ng pakiramdam",
    th: "ลักษณะ",
      de: "Art der Beschwerde",
      fr: "Nature",
      es: "Carácter",
    }),
  ccDurationTitle: L("多久了？", {
    en: "How long?",
    vi: "Bao lâu rồi?",
    id: "Sudah berapa lama?",
    ja: "どのくらいですか？",
    ko: "얼마나 됐나요?",
    fil: "Gaano katagal?",
    th: "นานแค่ไหน?",
      de: "Seit wann?",
      fr: "Depuis combien de temps ?",
      es: "¿Desde cuándo?",
    }),
  ccDuration: L("多久了 · 時長", {
    en: "How long · Duration",
    vi: "Bao lâu",
    id: "Durasi",
    ja: "どのくらい・時間",
    ko: "얼마나 · 기간",
    fil: "Gaano katagal",
    th: "นานแค่ไหน",
      de: "Seit wann · Dauer",
      fr: "Depuis quand · Durée",
      es: "¿Desde cuándo · Duración",
    }),
  intakeYesterday: L("昨天", {
    en: "Yesterday",
    vi: "Hôm qua",
    id: "Kemarin",
    ja: "昨日",
    ko: "어제",
    fil: "Kahapon",
    th: "เมื่อวาน",
      de: "Gestern",
      fr: "Hier",
      es: "Ayer",
    }),
  intakeToday: L("今天", {
    en: "Today",
    vi: "Hôm nay",
    id: "Hari ini",
    ja: "今日",
    ko: "오늘",
    fil: "Ngayong araw",
    th: "วันนี้",
      de: "Heute",
      fr: "Aujourd'hui",
      es: "Hoy",
    }),
  ccDurationAbout: L("約", {
    en: "About",
    vi: "Khoảng",
    id: "Sekitar",
    ja: "約",
    ko: "약",
    fil: "Mga",
    th: "ประมาณ",
      de: "Etwa",
      fr: "Environ",
      es: "Aproximadamente",
    }),
  ccDurationPreview: L("對照顯示", {
    en: "Shown as",
    vi: "Hiển thị",
    id: "Ditampilkan",
    ja: "表示",
    ko: "표시",
    fil: "Ipapakita bilang",
    th: "แสดงเป็น",
      de: "Anzeige",
      fr: "Affiché comme",
      es: "Se muestra como",
    }),
  ccPeriod: L("或時段", {
    en: "Or period",
    vi: "Hoặc khoảng thời gian",
    id: "Atau periode",
    ja: "または時間帯",
    ko: "또는 시간대",
    fil: "O oras/panahon",
    th: "หรือช่วงเวลา",
      de: "Oder Zeitraum",
      fr: "Ou période",
      es: "O periodo",
    }),
  ccPain: L("疼痛指數 · Pain 1–10", {
    en: "Pain score 1–10",
    vi: "Mức đau 1–10",
    id: "Skala nyeri 1–10",
    ja: "痛みの強さ 1–10",
    ko: "통증 점수 1–10",
    fil: "Antas ng sakit 1–10",
    th: "ระดับปวด 1–10",
      de: "Schmerzskala 1–10",
      fr: "Douleur 1–10",
      es: "Dolor 1–10",
    }),
  selectLanguage: L("選擇語言", {
    en: "Choose language",
    vi: "Chọn ngôn ngữ",
    id: "Pilih bahasa",
    ja: "言語を選ぶ",
    ko: "언어 선택",
    fil: "Pumili ng wika",
    th: "เลือกภาษา",
      de: "Sprache wählen",
      fr: "Choisir la langue",
      es: "Elegir idioma",
    }),
  informantAsking: L("正在回答問題的是：", {
    en: "Who is answering?",
    vi: "Người đang trả lời là:",
    id: "Yang sedang menjawab adalah:",
    ja: "今答えているのは：",
    ko: "지금 답하는 사람은:",
    fil: "Sino ang sumasagot:",
    th: "คนที่กำลังตอบคือ:",
    de: "Wer beantwortet gerade die Fragen?",
    fr: "Qui répond aux questions ?",
    es: "¿Quién está respondiendo?",
  }),
  traumaMechanismTitle: L("受傷機轉", {
    en: "Injury mechanism",
    vi: "Cơ chế chấn thương",
    id: "Mekanisme cedera",
    ja: "受傷機転",
    ko: "손상 기전",
    fil: "Mekanismo ng pinsala",
    th: "กลไกการบาดเจ็บ",
    de: "Verletzungsmechanismus",
    fr: "Mécanisme lésionnel",
    es: "Mecanismo de lesión",
  }),
  traumaBodyTitle: L("受傷部位", {
    en: "Injured area",
    vi: "Vùng bị thương",
    id: "Area cedera",
    ja: "受傷部位",
    ko: "손상 부위",
    fil: "Bahaging nasaktan",
    th: "ตำแหน่งที่บาดเจ็บ",
    de: "Verletzte Region",
    fr: "Zone blessée",
    es: "Zona lesionada",
  }),
  traumaVehicleTitle: L("車輛種類", {
    en: "Vehicle type",
    vi: "Loại xe",
    id: "Jenis kendaraan",
    ja: "車両の種類",
    ko: "차량 종류",
    fil: "Uri ng sasakyan",
    th: "ประเภทยานพาหนะ",
    de: "Fahrzeugart",
    fr: "Type de véhicule",
    es: "Tipo de vehículo",
  }),
  traumaInjuryTitle: L("傷類", {
    en: "Injury type",
    vi: "Loại chấn thương",
    id: "Jenis cedera",
    ja: "外傷の種類",
    ko: "손상 유형",
    fil: "Uri ng pinsala",
    th: "ประเภทการบาดเจ็บ",
    de: "Verletzungsart",
    fr: "Type de blessure",
    es: "Tipo de lesión",
  }),
  traumaFallHeight: L("墜落高度（公尺）", {
    en: "Fall height (meters)",
    vi: "Độ cao ngã (mét)",
    id: "Tinggi jatuh (meter)",
    ja: "墜落高さ（メートル）",
    ko: "추락 높이(미터)",
    fil: "Taas ng pagbagsak (metro)",
    th: "ความสูงที่ตก (เมตร)",
    de: "Sturzhöhe (Meter)",
    fr: "Hauteur de chute (mètres)",
    es: "Altura de caída (metros)",
  }),
  sceneTypeAsking: L("現場是：", {
    en: "Scene type:",
    vi: "Hiện trường là:",
    id: "Jenis kejadian:",
    ja: "現場の区分：",
    ko: "현장 유형:",
    fil: "Uri ng eksena:",
    th: "ลักษณะเหตุการณ์:",
    de: "Einsatzart:",
    fr: "Type de scène :",
    es: "Tipo de escena:",
  }),
  senseTitle: L("還有其他不舒服嗎？", {
    en: "Any other discomfort?",
    vi: "Còn khó chịu nào khác?",
    id: "Ada keluhan lain?",
    ja: "他に具合の悪い所は？",
    ko: "다른 불편한 곳이 있나요?",
    fil: "May iba pa bang hindi komportable?",
    th: "ยังมีอาการอื่นอีกไหม?",
      de: "Noch andere Beschwerden?",
      fr: "D'autres gênes ?",
      es: "¿Alguna otra molestia?",
    }),
  senseLead: L("一輪二次掃描", {
    en: "One extra pass",
    vi: "Chỉ hỏi thêm một lần",
    id: "Satu pemeriksaan tambahan",
    ja: "追加で一回だけ確認",
    ko: "한 번 더 확인",
    fil: "Isang karagdagang check",
    th: "ตรวจถามเพิ่มอีกครั้ง",
      de: "Eine zusätzliche Prüfung",
      fr: "Un passage supplémentaire",
      es: "Una revisión adicional",
    }),
  senseSymptoms: L("伴隨症狀", {
    en: "Accompanying",
    vi: "Triệu chứng kèm theo",
    id: "Gejala penyerta",
    ja: "随伴症状",
    ko: "동반 증상",
    fil: "Kasamang sintomas",
    th: "อาการร่วม",
      de: "Begleiterscheinungen",
      fr: "Symptômes associés",
      es: "Síntomas acompañantes",
    }),
  senseBody: L("可再指部位", {
    en: "Optional body scan",
    vi: "Có thể chỉ thêm vị trí",
    id: "Boleh tunjuk bagian lagi",
    ja: "部位を追加で指せます",
    ko: "부위를 더 가리킬 수 있음",
    fil: "Puwedeng tumuro ulit",
    th: "ชี้ตำแหน่งเพิ่มได้",
      de: "Körperstelle optional",
      fr: "Zone du corps facultative",
      es: "Zona del cuerpo opcional",
    }),
} as const satisfies Record<string, BilingualText>;
